### PR TITLE
leaflet-circle shortcode

### PR DESCRIPTION
**Pull request by peteruithoven**
Adds support for a leaflet-circle shortcode. 
Example:
```
[leaflet-circle message="max distance" lng=5 lat=52 radius=17500 color="#0DC143" fillOpacity=0.1]
```

I've tried to also add some documentation and examples. 

Please let me know if there is something that I can improve.

### CODE REVIEW

**Comment by bozdoz** [comment]
@peteruithoven this looks incredible. Thanks! I'll take a look at the the implementation asap!

**Comment by bozdoz** [comment]
I would love to have the ability to use the geocoder in this plugin too:

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/shortcodes/class.marker-shortcode.php#L39-L48

If you just added that to your lat/lng variables, that should work (maybe I should someday have that callable from another class so it's not repeated everywhere; something like `getLatLng($atts)`).

I would also like if it inherited it's location (by default) from the map: 

https://github.com/bozdoz/wp-plugin-leaflet-map/blob/master/shortcodes/class.marker-shortcode.php#L171-L182

Ideally, I would like to see this work:

```
[leaflet-map]
[leaflet-circle]
```

And just have it work with a default map and a default circle (radius, color, location, etc.)

Let me know what you think!  And thanks again!  Otherwise, looks great!  😃

**Comment by peteruithoven** [comment]
I really like the shared getLatLng idea (where it checks that address, map center etc), but I'll indeed repeat the code for this PR. 

Good points, I'm implementing those suggestions. 

With the new changes I'm getting the following map using default settings and the following code:
```
[leaflet-map]
[leaflet-circle]
````
screenshot from 2018-09-18 17-15-47

**Comment by bozdoz** [comment]
Looks great!  Works with geocoding and fitbounds too!

```
[leaflet-map]

[leaflet-circle address="san diego" fitbounds=1]
```

screen shot 2018-09-18 at 1 09 28 pm

One last nit-pick: The shortcode helper page example says "w/ScrollWheel".  I would suggest adding `scrollwheel=1` to the leaflet-map atts, or just removing that from the title.  Thanks again!

**Comment by bozdoz** [comment]
Thanks!

**Comment by peteruithoven** [comment]
Nice, thanks for testing that too. Thanks for the merge! 
I'm looking forward to the next release ;)

**Comment by peteruithoven** [comment]
Could you perhaps share a ETA for a next release? 
I noticed that the releases on github aren't in sync with releases on Wordpress, which makes it a bit harder to know when a new release arrived.

**Comment by bozdoz** [comment]
Should be live now;  v2.11.3;  the previous version introduced a small/obvious bug

**Comment by peteruithoven** [comment]
Thanks! 
Latest WIP, now with ring: http://vokoutrecht.nl.transurl.nl/kaart-inline/

**Pull request merged**
